@startuml

Class ComputeVAT{
     + static Dialog dialog
     + static CalculateVAT calc
     + static View view
     + int PRCVAT = 25;
     + String MSG = "MOMS";
     + String CURRENCY = "Kr";
     + Main()
}
ComputeVAT -> Controller
Class Controller{
    runController(View, CalculateVAT, Dialog)
    + String MSG = "MOMS";
    + double userIn = dialog.doDiag();
    + double moms = calc.doVAT(userIn);
    view.doView(moms,MSG);
}
Controller -> View


Class View{

    + static void doView(double result, String typeOfResult)
    - String MSG = "MOMS";
    - String CURRENCY = "Kr";

}

Controller -> Dialog

Class Dialog{
    + public static double doDiag();
    - Scanner myScan = new Scanner(System.in);
    - double number = myScan.nextDouble();

}

Controller -> CalculateVAT
Class CalculateVAT{
    + static double doVAT(double number)
    - int PRCVAT = 25;
    - double VAT = number / 100 * PRCVAT;

}

@enduml